"""Pre-LLM content filter — hardcoded guardrails.

Runs BEFORE the LLM call. Detects hate speech, discriminatory content,
and prompt injection attempts via pattern matching. Returns a fixed
response string (NOT generated by the LLM) to prevent manipulation.

Spec §13.1 — Ethical Guardrails.
"""

import logging
import re
from typing import NamedTuple

from src.core.config import config as app_config

logger = logging.getLogger("backend.guardrails")


class GuardrailResult(NamedTuple):
    triggered: bool
    response: str  # Fixed response in session language (empty if not triggered)
    category: str  # "hate_speech" | "prompt_injection" | "" (empty if not triggered)


# ---------------------------------------------------------------------------
# Pattern definitions
# ---------------------------------------------------------------------------

# Hate speech / discriminatory patterns — kept broad but focused on
# content that attributes problems to protected characteristics or uses
# slurs/dehumanizing language. These are NOT intended to catch nuanced
# cases (the prompt-layer guardrails handle those) — this is a first-pass
# filter for obvious violations.

_HATE_PATTERNS: list[re.Pattern] = [
    # Slurs and dehumanizing language (multi-language core terms)
    re.compile(r"\b(subhuman|untermenschen?|cockroach(?:es)?|vermin|parasit(?:e|es|en))\b", re.IGNORECASE),
    # Explicit calls for violence against groups
    re.compile(r"\b(kill\s+(?:all|every|the)\s+\w+|exterminate|ethnic\s+cleansing|genocide)\b", re.IGNORECASE),
    # Explicit racial/ethnic supremacy
    re.compile(r"\b(\w+\s+(?:supremacy|are\s+(?:inferior|subhuman|animals)))\b", re.IGNORECASE),
    # "Workers from [group] are/should be..." discriminatory framing
    re.compile(r"\b(workers?\s+from\s+\w+\s+(?:are|should\s+be)\s+(?:fired|deported|removed|eliminated))\b", re.IGNORECASE),
]

# Prompt injection — attempts to override system instructions, reveal
# the system prompt, or assume a different identity.

_INJECTION_PATTERNS: list[re.Pattern] = [
    # Direct override attempts
    re.compile(r"ignore\s+(?:all\s+)?(?:your|previous|prior|above)\s+(?:instructions?|rules?|prompt)", re.IGNORECASE),
    re.compile(r"disregard\s+(?:all\s+)?(?:your|previous|prior|above)\s+(?:instructions?|rules?|prompt)", re.IGNORECASE),
    re.compile(r"forget\s+(?:all\s+)?(?:your|previous|prior|above)\s+(?:instructions?|rules?|prompt)", re.IGNORECASE),
    # Identity override
    re.compile(r"you\s+are\s+now\s+(?:a\s+)?(?:different|new|my)\s+", re.IGNORECASE),
    re.compile(r"(?:act|behave|pretend|respond)\s+as\s+(?:if\s+you\s+(?:are|were)\s+)?(?:a\s+)?(?:different|evil|unfiltered|unrestricted|jailbroken)", re.IGNORECASE),
    # System prompt extraction
    re.compile(r"(?:show|reveal|print|output|repeat|display)\s+(?:me\s+)?(?:your|the)\s+(?:system\s+)?(?:prompt|instructions?|rules?)", re.IGNORECASE),
    re.compile(r"what\s+(?:are|is)\s+your\s+(?:system\s+)?(?:prompt|instructions?|initial\s+prompt)", re.IGNORECASE),
    # DAN-style jailbreaks
    re.compile(r"\bDAN\b.*(?:do\s+anything\s+now|no\s+restrictions)", re.IGNORECASE),
    re.compile(r"(?:developer|debug|admin|sudo|root)\s+mode", re.IGNORECASE),
]


# ---------------------------------------------------------------------------
# Fixed responses per language — hardcoded, never LLM-generated.
# EN/ES/FR are proper translations. Others use English fallback until
# the dedicated translation sprint.
# ---------------------------------------------------------------------------

_FIXED_RESPONSES: dict[str, str] = {
    "en": "Your message contains content that conflicts with this system's ethical principles. I'm here to help with labor rights documentation. If you'd like to continue on that basis, I'm ready to help.",
    "es": "Tu mensaje contiene contenido que entra en conflicto con los principios éticos de este sistema. Estoy aquí para ayudar con la documentación de derechos laborales. Si deseas continuar sobre esa base, estoy listo para ayudar.",
    "fr": "Votre message contient du contenu qui entre en conflit avec les principes éthiques de ce système. Je suis ici pour aider à la documentation des droits du travail. Si vous souhaitez continuer sur cette base, je suis prêt à vous aider.",
    "de": "Ihre Nachricht enthält Inhalte, die den ethischen Grundsätzen dieses Systems widersprechen. Ich bin hier, um bei der Dokumentation von Arbeitsrechten zu helfen. Wenn Sie auf dieser Grundlage fortfahren möchten, bin ich bereit zu helfen.",
    "pt": "Sua mensagem contém conteúdo que conflita com os princípios éticos deste sistema. Estou aqui para ajudar com a documentação de direitos trabalhistas. Se deseja continuar nessa base, estou pronto para ajudar.",
    "it": "Il tuo messaggio contiene contenuti in conflitto con i principi etici di questo sistema. Sono qui per aiutare con la documentazione dei diritti dei lavoratori. Se desideri continuare su questa base, sono pronto ad aiutarti.",
}

_SESSION_ENDED_RESPONSES: dict[str, str] = {
    "en": "This session has been ended due to repeated policy violations. If you need assistance with labor rights documentation, please start a new session.",
    "es": "Esta sesión ha sido finalizada debido a violaciones repetidas de la política de uso. Si necesitas asistencia con documentación de derechos laborales, por favor inicia una nueva sesión.",
    "fr": "Cette session a été terminée en raison de violations répétées de la politique d'utilisation. Si vous avez besoin d'aide pour la documentation des droits du travail, veuillez démarrer une nouvelle session.",
    "de": "Diese Sitzung wurde aufgrund wiederholter Richtlinienverstöße beendet. Wenn Sie Hilfe bei der Dokumentation von Arbeitsrechten benötigen, starten Sie bitte eine neue Sitzung.",
    "pt": "Esta sessão foi encerrada devido a violações repetidas da política de uso. Se precisar de assistência com documentação de direitos trabalhistas, por favor inicie uma nova sessão.",
    "it": "Questa sessione è stata terminata a causa di ripetute violazioni della politica d'uso. Se hai bisogno di assistenza con la documentazione dei diritti dei lavoratori, avvia una nuova sessione.",
}


def _get_response(language: str, ended: bool = False) -> str:
    """Get fixed response in session language, English fallback."""
    responses = _SESSION_ENDED_RESPONSES if ended else _FIXED_RESPONSES
    return responses.get(language, responses["en"])


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def check_content(content: str, language: str = "en") -> GuardrailResult:
    """Check user message content against guardrail patterns.

    Returns a GuardrailResult indicating whether the content was flagged
    and the fixed response to return (if any).

    This runs BEFORE the LLM call. Only checks the user's message text,
    not the full conversation context.
    """
    if not app_config.guardrails_enabled:
        return GuardrailResult(triggered=False, response="", category="")

    # Check hate speech patterns
    for pattern in _HATE_PATTERNS:
        match = pattern.search(content)
        if match:
            logger.warning(f"Guardrail triggered (hate_speech): matched '{match.group()}' in user content")
            return GuardrailResult(
                triggered=True,
                response=_get_response(language),
                category="hate_speech",
            )

    # Check prompt injection patterns
    for pattern in _INJECTION_PATTERNS:
        match = pattern.search(content)
        if match:
            logger.warning(f"Guardrail triggered (prompt_injection): matched '{match.group()}' in user content")
            return GuardrailResult(
                triggered=True,
                response=_get_response(language),
                category="prompt_injection",
            )

    return GuardrailResult(triggered=False, response="", category="")


def get_session_ended_response(language: str = "en") -> str:
    """Get the fixed response for when a session is ended due to violations."""
    return _get_response(language, ended=True)
